p8105_hw2_wl2926
================
Wenwen Li
2023-10-03

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.3     ✔ readr     2.1.4
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.0
    ## ✔ ggplot2   3.4.3     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.2     ✔ tidyr     1.3.0
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(readxl)
library(dplyr)
```

\#Problem 2

\##Part 1:Read and clean the Mr. Trash Wheel sheet

``` r
###specify the sheet in the Excel file and to omit non-data entries (rows with notes / figures;   columns containing notes) using arguments in read_excel
data = read_excel("data/202309 Trash Wheel Collection Data.xlsx", sheet = "Mr. Trash Wheel", range = "A2:N586")

###omit rows that do not include dumpster-specific data
data_TW <- data %>%
  drop_na(Dumpster)

##Print the cleaned data
print(data)
```

    ## # A tibble: 584 × 14
    ##    Dumpster Month Year  Date                `Weight (tons)`
    ##       <dbl> <chr> <chr> <dttm>                        <dbl>
    ##  1        1 May   2014  2014-05-16 00:00:00            4.31
    ##  2        2 May   2014  2014-05-16 00:00:00            2.74
    ##  3        3 May   2014  2014-05-16 00:00:00            3.45
    ##  4        4 May   2014  2014-05-17 00:00:00            3.1 
    ##  5        5 May   2014  2014-05-17 00:00:00            4.06
    ##  6        6 May   2014  2014-05-20 00:00:00            2.71
    ##  7        7 May   2014  2014-05-21 00:00:00            1.91
    ##  8        8 May   2014  2014-05-28 00:00:00            3.7 
    ##  9        9 June  2014  2014-06-05 00:00:00            2.52
    ## 10       10 June  2014  2014-06-11 00:00:00            3.76
    ## # ℹ 574 more rows
    ## # ℹ 9 more variables: `Volume (cubic yards)` <dbl>, `Plastic Bottles` <dbl>,
    ## #   Polystyrene <dbl>, `Cigarette Butts` <dbl>, `Glass Bottles` <dbl>,
    ## #   `Plastic Bags` <dbl>, Wrappers <dbl>, `Sports Balls` <dbl>,
    ## #   `Homes Powered*` <dbl>

\##Part 2: Update the data to include a new homes_powered variable based
on this calculation

``` r
# Calculate homes powered based on the trash (in tonnes)
data <- data %>%
  rename(
    trash_tonnes = `Weight (tons)`, 
    homes_powered = `Homes Powered*` 
   )
# Each ton of trash equates to 500 kilowatts of electricity, and an average household uses 30 kilowatts per day
data$homes_powered <- data$trash_tonnes * (500 / 30)  # Calculate homes powered

# Print the updated data frame
print(data)
```

    ## # A tibble: 584 × 14
    ##    Dumpster Month Year  Date                trash_tonnes `Volume (cubic yards)`
    ##       <dbl> <chr> <chr> <dttm>                     <dbl>                  <dbl>
    ##  1        1 May   2014  2014-05-16 00:00:00         4.31                     18
    ##  2        2 May   2014  2014-05-16 00:00:00         2.74                     13
    ##  3        3 May   2014  2014-05-16 00:00:00         3.45                     15
    ##  4        4 May   2014  2014-05-17 00:00:00         3.1                      15
    ##  5        5 May   2014  2014-05-17 00:00:00         4.06                     18
    ##  6        6 May   2014  2014-05-20 00:00:00         2.71                     13
    ##  7        7 May   2014  2014-05-21 00:00:00         1.91                      8
    ##  8        8 May   2014  2014-05-28 00:00:00         3.7                      16
    ##  9        9 June  2014  2014-06-05 00:00:00         2.52                     14
    ## 10       10 June  2014  2014-06-11 00:00:00         3.76                     18
    ## # ℹ 574 more rows
    ## # ℹ 8 more variables: `Plastic Bottles` <dbl>, Polystyrene <dbl>,
    ## #   `Cigarette Butts` <dbl>, `Glass Bottles` <dbl>, `Plastic Bags` <dbl>,
    ## #   Wrappers <dbl>, `Sports Balls` <dbl>, homes_powered <dbl>

\##Part 3 Use a similar process to import, clean, and organize the data
for Professor Trash Wheel and Gwynnda, and combine these with the
Mr. Trash Wheel dataset to produce a single tidy dataset.

``` r
###For Professor Trash Wheel:omit the irrelavent data
data_df_prof = read_excel("data/202309 Trash Wheel Collection Data.xlsx", sheet = "Professor Trash Wheel", range = "A2:M108")

###omit rows that do not include dumpster-specific data
data_cl_df_prof<- data_df_prof %>%
  drop_na(Dumpster)

print(data_cl_df_prof)
```

    ## # A tibble: 106 × 13
    ##    Dumpster Month     Year Date                `Weight (tons)`
    ##       <dbl> <chr>    <dbl> <dttm>                        <dbl>
    ##  1        1 January   2017 2017-01-02 00:00:00            1.79
    ##  2        2 January   2017 2017-01-30 00:00:00            1.58
    ##  3        3 February  2017 2017-02-26 00:00:00            2.32
    ##  4        4 February  2017 2017-02-26 00:00:00            3.72
    ##  5        5 February  2017 2017-02-28 00:00:00            1.45
    ##  6        6 March     2017 2017-03-30 00:00:00            1.71
    ##  7        7 April     2017 2017-04-01 00:00:00            1.82
    ##  8        8 April     2017 2017-04-20 00:00:00            2.37
    ##  9        9 May       2017 2017-05-10 00:00:00            2.64
    ## 10       10 May       2017 2017-05-26 00:00:00            2.78
    ## # ℹ 96 more rows
    ## # ℹ 8 more variables: `Volume (cubic yards)` <dbl>, `Plastic Bottles` <dbl>,
    ## #   Polystyrene <dbl>, `Cigarette Butts` <dbl>, `Glass Bottles` <dbl>,
    ## #   `Plastic Bags` <dbl>, Wrappers <dbl>, `Homes Powered*` <dbl>

``` r
###For Gwynnda Trash Wheel:omit the irrelavent data
data_df_Gwy = read_excel("data/202309 Trash Wheel Collection Data.xlsx", sheet = "Gwynnda Trash Wheel", range = "A2:L157")

###omit rows that do not include dumpster-specific data
data_cl_df_Gwy<- data_df_prof %>%
  drop_na(Dumpster)

print(data_cl_df_Gwy)
```

    ## # A tibble: 106 × 13
    ##    Dumpster Month     Year Date                `Weight (tons)`
    ##       <dbl> <chr>    <dbl> <dttm>                        <dbl>
    ##  1        1 January   2017 2017-01-02 00:00:00            1.79
    ##  2        2 January   2017 2017-01-30 00:00:00            1.58
    ##  3        3 February  2017 2017-02-26 00:00:00            2.32
    ##  4        4 February  2017 2017-02-26 00:00:00            3.72
    ##  5        5 February  2017 2017-02-28 00:00:00            1.45
    ##  6        6 March     2017 2017-03-30 00:00:00            1.71
    ##  7        7 April     2017 2017-04-01 00:00:00            1.82
    ##  8        8 April     2017 2017-04-20 00:00:00            2.37
    ##  9        9 May       2017 2017-05-10 00:00:00            2.64
    ## 10       10 May       2017 2017-05-26 00:00:00            2.78
    ## # ℹ 96 more rows
    ## # ℹ 8 more variables: `Volume (cubic yards)` <dbl>, `Plastic Bottles` <dbl>,
    ## #   Polystyrene <dbl>, `Cigarette Butts` <dbl>, `Glass Bottles` <dbl>,
    ## #   `Plastic Bags` <dbl>, Wrappers <dbl>, `Homes Powered*` <dbl>

### Combine Datasets

``` r
  # Convert the "Year" column to character in both datasets
data_cl_df_Gwy <- mutate(data_cl_df_Gwy, Year = as.character(Year))
data_cl_df_prof <- mutate(data_cl_df_prof, Year = as.character(Year))

# Now, you should be able to combine the datasets without the type mismatch error
combined_data <- bind_rows(data_cl_df_Gwy, data_cl_df_prof, data)
print(combined_data) 
```

    ## # A tibble: 796 × 16
    ##    Dumpster Month    Year  Date                `Weight (tons)`
    ##       <dbl> <chr>    <chr> <dttm>                        <dbl>
    ##  1        1 January  2017  2017-01-02 00:00:00            1.79
    ##  2        2 January  2017  2017-01-30 00:00:00            1.58
    ##  3        3 February 2017  2017-02-26 00:00:00            2.32
    ##  4        4 February 2017  2017-02-26 00:00:00            3.72
    ##  5        5 February 2017  2017-02-28 00:00:00            1.45
    ##  6        6 March    2017  2017-03-30 00:00:00            1.71
    ##  7        7 April    2017  2017-04-01 00:00:00            1.82
    ##  8        8 April    2017  2017-04-20 00:00:00            2.37
    ##  9        9 May      2017  2017-05-10 00:00:00            2.64
    ## 10       10 May      2017  2017-05-26 00:00:00            2.78
    ## # ℹ 786 more rows
    ## # ℹ 11 more variables: `Volume (cubic yards)` <dbl>, `Plastic Bottles` <dbl>,
    ## #   Polystyrene <dbl>, `Cigarette Butts` <dbl>, `Glass Bottles` <dbl>,
    ## #   `Plastic Bags` <dbl>, Wrappers <dbl>, `Homes Powered*` <dbl>,
    ## #   trash_tonnes <dbl>, `Sports Balls` <dbl>, homes_powered <dbl>

In Mr.Trash Wheel dataset there are **584** observations and **14**
features.In combined dataset there are **796** observations and **16**
features.For example, Varaible ‘Dumpster’ is the number of people
dumbing the trash, and ‘Weight’ is the sum of the trashes. Based on the
combined dataset, we got 796 observations.The total weight collected by
Professor Trash Wheel is 216.26 tons;The total number of cigarette butts
collected by Gwynnda is 16300 in July of 2021.

\#Problem 3 \##Import, clean, and tidy the dataset of baseline
demographics.

``` r
data_MCI = read_csv("data/MCI_baseline.csv",skip = 1)|>
janitor::clean_names() 
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): Age at onset
    ## dbl (5): ID, Current Age, Sex, Education, apoe4
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
# Encoding 'sex' 'apoe4'as a factor
data_MCI$sex <-factor(data_MCI$sex, levels = c(0, 1), labels = c("Female", "Male"))
data_MCI$apoe4 <-factor(data_MCI$apoe4, levels = c(0, 1), labels = c("APOE4 noncarrier", "APOE4 carrier"))
print(data_MCI)
```

    ## # A tibble: 483 × 6
    ##       id current_age sex    education apoe4            age_at_onset
    ##    <dbl>       <dbl> <fct>      <dbl> <fct>            <chr>       
    ##  1     1        63.1 Female        16 APOE4 carrier    .           
    ##  2     2        65.6 Female        20 APOE4 carrier    .           
    ##  3     3        62.5 Male          16 APOE4 carrier    66.8        
    ##  4     4        69.8 Female        16 APOE4 noncarrier .           
    ##  5     5        66   Male          16 APOE4 noncarrier 68.7        
    ##  6     6        62.5 Male          16 APOE4 noncarrier .           
    ##  7     7        66.5 Male          18 APOE4 noncarrier 74          
    ##  8     8        67.2 Female        18 APOE4 noncarrier .           
    ##  9     9        66.7 Female        16 APOE4 noncarrier .           
    ## 10    10        64.1 Female        18 APOE4 noncarrier .           
    ## # ℹ 473 more rows

``` r
#remove any participants who do not meet the stated inclusion criteria (i.e. no MCI at baseline)
filtered_data_MCI <- data_MCI[data_MCI$age_at_onset != ".", , drop = TRUE]

mean1 =  mean(data_MCI$current_age, na.rm = TRUE)

# Calculate the proportion of women who are APOE4 carriers
total_women <- sum(data_MCI$sex == "Female")  # Total number of women (assuming 0 represents female)
women_APOE4_carriers <- sum(data_MCI$sex == "Female" & data_MCI$apoe4 == "APOE4 carrier") 
proportion = women_APOE4_carriers / total_women

print(filtered_data_MCI)
```

    ## # A tibble: 97 × 6
    ##       id current_age sex    education apoe4            age_at_onset
    ##    <dbl>       <dbl> <fct>      <dbl> <fct>            <chr>       
    ##  1     3        62.5 Male          16 APOE4 carrier    66.8        
    ##  2     5        66   Male          16 APOE4 noncarrier 68.7        
    ##  3     7        66.5 Male          18 APOE4 noncarrier 74          
    ##  4    13        63.1 Male          12 APOE4 carrier    69          
    ##  5    14        58.4 Female        20 APOE4 noncarrier 66.2        
    ##  6    18        67.8 Male          16 APOE4 noncarrier 69.8        
    ##  7    22        67.3 Female        20 APOE4 carrier    74.6        
    ##  8    26        64.8 Female        20 APOE4 carrier    71.1        
    ##  9    30        66.3 Female        12 APOE4 noncarrier 73.1        
    ## 10    39        68.3 Female        16 APOE4 carrier    70.2        
    ## # ℹ 87 more rows

Discuss important steps in the import process and relevant features of
the dataset. How many participants were recruited, and of these how many
develop MCI? What is the average baseline age? What proportion of women
in the study are APOE4 carriers? When we try to import the dataset, we
have to choose the correct format, and omit the columns and rows like
figures, notes, description when we want to do a data analysis. There
are **483** observations and **6** features. Only **97** develop MCI.
The average baseline age should be **`mean1`** The proportion of women
are APOE 4 carriers is **`proportion`**

\##Step 2

``` r
mci_amyloid = read_csv("data/mci_amyloid.csv",skip = 1)|>
janitor::clean_names()
```

    ## Rows: 487 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (5): Baseline, Time 2, Time 4, Time 6, Time 8
    ## dbl (1): Study ID
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
# Clean names
mci_amyloid <- janitor::clean_names(mci_amyloid)
long_amyloid<-pivot_longer(data = mci_amyloid,
                          cols = "baseline", 
                           names_to = "Timepoint", 
                           values_to = "Biomarker_value") 
long_amyloid[2:495,  ]
```

    ## # A tibble: 494 × 7
    ##    study_id time_2      time_4      time_6      time_8 Timepoint Biomarker_value
    ##       <dbl> <chr>       <chr>       <chr>       <chr>  <chr>     <chr>          
    ##  1        2 0.109157373 0.109457839 0.105729713 0.106… baseline  0.107481183    
    ##  2        3 0.108744509 0.106065035 <NA>        0.106… baseline  0.106087034    
    ##  3        4 0.108699686 0.110540386 0.107476797 0.111… baseline  0.109251358    
    ##  4        5 0.112273883 0.115139677 0.106606054 0.106… baseline  0.107950408    
    ##  5        6 0.112853415 0.11143945  0.110279277 0.114… baseline  0.112426974    
    ##  6        7 <NA>        0.104251905 0.112485583 0.112… baseline  0.112246391    
    ##  7        8 0.109470828 <NA>        0.108742168 0.110… baseline  0.109563372    
    ##  8        9 0.109781199 0.108832888 <NA>        <NA>   baseline  0.112101884    
    ##  9       10 0.111592149 <NA>        <NA>        0.110… baseline  0.1116094      
    ## 10       11 0.109316496 0.1114037   0.108586573 0.108… baseline  0.109119335    
    ## # ℹ 484 more rows

``` r
# Print the tidied dataset
head("long_amyloid")
```

    ## [1] "long_amyloid"

We use “read_csv” to import the dataset, and first step should be clean
and tidy the dataset. This dataset have long numrical data, so we could
use the “pivot_longer()”to figure it out.There are **487** observations
and **6** features.

\###Combine the demographic and biomarker datasets

``` r
#rename the first column
data_MCI<- data_MCI %>%
  rename(study_id = id)
print("Updated Dataset:")
```

    ## [1] "Updated Dataset:"

``` r
print(data_MCI)
```

    ## # A tibble: 483 × 6
    ##    study_id current_age sex    education apoe4            age_at_onset
    ##       <dbl>       <dbl> <fct>      <dbl> <fct>            <chr>       
    ##  1        1        63.1 Female        16 APOE4 carrier    .           
    ##  2        2        65.6 Female        20 APOE4 carrier    .           
    ##  3        3        62.5 Male          16 APOE4 carrier    66.8        
    ##  4        4        69.8 Female        16 APOE4 noncarrier .           
    ##  5        5        66   Male          16 APOE4 noncarrier 68.7        
    ##  6        6        62.5 Male          16 APOE4 noncarrier .           
    ##  7        7        66.5 Male          18 APOE4 noncarrier 74          
    ##  8        8        67.2 Female        18 APOE4 noncarrier .           
    ##  9        9        66.7 Female        16 APOE4 noncarrier .           
    ## 10       10        64.1 Female        18 APOE4 noncarrier .           
    ## # ℹ 473 more rows

``` r
x = data_MCI
y = mci_amyloid
merged_data <- left_join(x, y, by = "study_id")

# Print the merged dataset
print("Merged Dataset:")
```

    ## [1] "Merged Dataset:"

``` r
print(merged_data)
```

    ## # A tibble: 483 × 11
    ##    study_id current_age sex    education apoe4      age_at_onset baseline time_2
    ##       <dbl>       <dbl> <fct>      <dbl> <fct>      <chr>        <chr>    <chr> 
    ##  1        1        63.1 Female        16 APOE4 car… .            0.11054… <NA>  
    ##  2        2        65.6 Female        20 APOE4 car… .            0.10748… 0.109…
    ##  3        3        62.5 Male          16 APOE4 car… 66.8         0.10608… 0.108…
    ##  4        4        69.8 Female        16 APOE4 non… .            0.10925… 0.108…
    ##  5        5        66   Male          16 APOE4 non… 68.7         0.10795… 0.112…
    ##  6        6        62.5 Male          16 APOE4 non… .            0.11242… 0.112…
    ##  7        7        66.5 Male          18 APOE4 non… 74           0.11224… <NA>  
    ##  8        8        67.2 Female        18 APOE4 non… .            0.10956… 0.109…
    ##  9        9        66.7 Female        16 APOE4 non… .            0.11210… 0.109…
    ## 10       10        64.1 Female        18 APOE4 non… .            0.11160… 0.111…
    ## # ℹ 473 more rows
    ## # ℹ 3 more variables: time_4 <chr>, time_6 <chr>, time_8 <chr>

``` r
file_path <- "data/merged_data.csv"
write.csv(merged_data, file = file_path, row.names = FALSE)
```

There are **483** observations and **11** features.There are three
people who are in the MCI baseline dataset, but not in the mci amyloid
dataset. They only have the APOE, but don’t have the time. However, all
of them are showed in the merge table, maybe these three of them did not
do the biomarkers test.
